#ifndef _CC_MODE_H
#define _CC_MODE_H

#define FLAG_CC_MODE 0x01
#define FLAG_CC_AUDIT_LOGGING 0x02
#define FLAG_FORCE_CERT_VALIDATION 0x04
#define FLAG_FORCE_LIMIT_TLS_CIPHER_SUITES 0x08
#define FLAG_FORCE_LIMIT_TLS_ECC_ALG 0x10
#define FLAG_FORCE_USE_RANDOM_DEV 0x20

#endif
