#
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_LGE_SIC_SPI) += lge_touch_core_spi.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SIC_SPI) += touch_sic_spi.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SIC_SPI) += touch_sic_abt_spi.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SIC_SPI) += touch_sic_watch_font.o