ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSM_OTP) += msm_otp.o
ifeq ($(CONFIG_MSM_OTP), y)
obj-$(CONFIG_OV8858) += ov8858_otp.o
endif
