obj-$(CONFIG_MACH_LGE)				+= devices_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC)			+= lge_handle_panic.o
obj-$(CONFIG_LGE_EARJACK_DEBUGGER)		+= lge_earjack_debugger.o

obj-$(CONFIG_LGE_BOOTLOADER_LOG)		+= lge_bootloader_log.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER)	+= lge_bootloader_time_checker.o
obj-$(CONFIG_WIFI_CONTROL_FUNC)			+= wifi_bcm_lge.o
obj-$(CONFIG_LGE_PM)				+= lge_gpio_debug.o
obj-$(CONFIG_PRE_SELF_DIAGNOSIS) += lge_pre_selfd.o
obj-$(CONFIG_CHECK_CPU) += lge_fac_check_cpu.o
obj-$(CONFIG_CHECK_EMMC) += lge_fac_check_emmc.o
obj-$(CONFIG_CHECK_RAM) += lge_fac_check_ram.o
obj-$(CONFIG_CHECK_MATCHED) += lge_fac_check_matched.o
obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_LGE_QSDL_SUPPORT) += lge_qsdl.o
obj-$(CONFIG_LGE_PM_UNIFIED_NODE) += lge_power_sysfs.o
